import { existsSync } from "node:fs";
import { join } from "node:path";
import brandsJson from "@/data/brands.json";
import rolexWatches from "@/data/rolex/watches.json";
import omegaWatches from "@/data/omega/watches.json";
import patekWatches from "@/data/patek-philippe/watches.json";
import apWatches from "@/data/audemars-piguet/watches.json";
import jlcWatches from "@/data/jaeger-lecoultre/watches.json";
import cartierWatches from "@/data/cartier/watches.json";
import grandSeikoWatches from "@/data/grand-seiko/watches.json";
import type { Brand, BrandView, Watch, WatchView } from "./types";

const regionNames = new Intl.DisplayNames(["en"], { type: "region" });

const brands: BrandView[] = (brandsJson as Brand[]).map((brand) => ({
  ...brand,
  logoSrc: brand.logo ? `/brands/${brand.id}/${brand.logo}` : null,
  countryName: regionNames.of(brand.country) ?? brand.country,
  countryCode: brand.country.toLowerCase(),
}));

const brandsById = new Map(brands.map((b) => [b.id, b]));

const watchesByBrand: Record<string, Watch[]> = {
  rolex: rolexWatches as Watch[],
  omega: omegaWatches as Watch[],
  "patek-philippe": patekWatches as Watch[],
  "audemars-piguet": apWatches as Watch[],
  "jaeger-lecoultre": jlcWatches as Watch[],
  cartier: cartierWatches as Watch[],
  "grand-seiko": grandSeikoWatches as Watch[],
};

function resolveAsset(brandId: string, p: string): string {
  return /^https?:\/\//.test(p) ? p : `/watches/${brandId}/${p}`;
}

const PUBLIC_DIR = join(process.cwd(), "public");

/**
 * The quiz uses a blurred sibling of the thumbnail (identifying text/logos
 * masked) named `<name>-quiz.webp`, generated by the `just quiz-prepare` tool.
 * It's resolved by convention — no JSON field — so dropping the file in is the
 * only step. Returns the variant's public URL when it exists on disk, else the
 * thumbnail itself.
 */
function quizSrc(thumbnailSrc: string): string {
  if (/^https?:\/\//.test(thumbnailSrc)) return thumbnailSrc; // remote, no local sibling
  const variant = thumbnailSrc.replace(/(\.[^./]+)$/, "-quiz$1");
  return variant !== thumbnailSrc && existsSync(join(PUBLIC_DIR, variant))
    ? variant
    : thumbnailSrc;
}

const watchViewsByBrand: Record<string, WatchView[]> = Object.fromEntries(
  Object.entries(watchesByBrand).map(([brandId, watches]) => [
    brandId,
    watches.map((w) => {
      const thumbnailSrc = resolveAsset(brandId, w.thumbnail);
      return {
        ...w,
        thumbnailSrc,
        thumbnailTestSrc: quizSrc(thumbnailSrc),
        imageSrcs: w.images.map((img) => resolveAsset(brandId, img)),
      };
    }),
  ]),
);

export function getBrands(): BrandView[] {
  return brands;
}

export function getBrand(id: string): BrandView | undefined {
  return brandsById.get(id);
}

export function getWatches(brandId: string): WatchView[] {
  return watchViewsByBrand[brandId] ?? [];
}

export function getWatch(
  brandId: string,
  watchId: string,
): WatchView | undefined {
  return getWatches(brandId).find((w) => w.id === watchId);
}

export function getLiveBrands(): BrandView[] {
  return brands.filter((b) => !b.comingSoon);
}
